### ISSUE TITLE
TODO List for emq2.0

### ISSUE THREAD

**Issue by vowstar** [emqtt/emq_kafka_bridge#2]
- [ ] Update plugin and make it works on emq2.0
- [ ] Use brod instead of ekaf
- [ ] Consume kafka's message on some topic and republish to mqtt(for m2m)
It looks these work will take some days, I'll try it...

**Comment by DigitalMarc** [comment]
Cheers vowstar! can't wait for starting using it
